import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { ArrowRight, Search, MapPin, CalendarCheck, Compass, TreePine, Landmark, Drama, Church, ChevronLeft, ChevronRight } from 'lucide-react';
import PlaceCard from '../components/PlaceCard';
import heroIsland from '../images/image1.jpeg';
import travelSigns from '../images/image2.jpeg';
import worldTraveller from '../images/image3.jpeg';
import sriLankaTravel from '../images/image4.jpeg';

const categories = [['Religious', Church], ['Nature', TreePine], ['Heritage', Landmark], ['Cultural', Drama]];
const heroSlides = [
  { src: sriLankaTravel, alt: 'Sri Lankan culture, wildlife and landmarks' },
  { src: heroIsland, alt: 'Tropical island with palm trees' },
  { src: travelSigns, alt: 'Illustrated nature, ocean and sunset travel signs' },
  { src: worldTraveller, alt: 'Traveller looking at a world map' },
];
const Home = () => {
  const [places, setPlaces] = useState([]); const [query, setQuery] = useState(''); const [slide, setSlide] = useState(() => Math.floor(Math.random() * heroSlides.length)); const navigate = useNavigate();
  useEffect(() => { axios.get(`${process.env.REACT_APP_API_URL}/places`).then(r => setPlaces(r.data.slice(0,3))).catch(() => {}); }, []);
  useEffect(() => { const timer = window.setInterval(() => setSlide(current => (current + 1) % heroSlides.length), 5000); return () => window.clearInterval(timer); }, []);
  const search = e => { e.preventDefault(); navigate(`/places${query.trim() ? `?search=${encodeURIComponent(query)}` : ''}`); };
  return <main className="flex-1">
    <section className="relative bg-primary-900 text-white overflow-hidden">
      <div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(circle at 1px 1px, white 1px, transparent 0)', backgroundSize:'28px 28px'}}/>
      <div className="section-shell relative grid lg:grid-cols-[1.08fr_.92fr] min-h-[650px] items-center gap-12 py-16">
        <div><p className="inline-flex items-center gap-2 text-secondary-300 text-xs font-bold uppercase tracking-[.2em]"><Compass size={16}/> Your next story is nearby</p><h1 className="text-5xl sm:text-6xl lg:text-7xl font-extrabold leading-[1.02] mt-6">Find wonder<br/><span className="text-secondary-300">close to home.</span></h1><p className="text-lg text-primary-100/75 max-w-xl leading-8 mt-6">Discover remarkable places within 25 km, get the details you need, and turn your favourites into a perfectly paced day trip.</p>
          <form onSubmit={search} className="mt-9 flex bg-white rounded-full p-2 max-w-xl shadow-2xl"><Search className="text-gray-400 ml-4 self-center" size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 px-3 text-primary-900 outline-none" placeholder="Search places near you..."/><button className="btn-secondary !py-3 px-6 flex items-center gap-2">Explore <ArrowRight size={17}/></button></form>
          <div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 text-sm text-primary-100/65"><span className="flex gap-2"><MapPin size={17} className="text-secondary-300"/>Within 25 km</span><span className="flex gap-2"><CalendarCheck size={17} className="text-secondary-300"/>Easy day planning</span><span className="flex gap-2"><Compass size={17} className="text-secondary-300"/>Local experiences</span></div>
        </div>
        <div className="relative max-w-xl w-full mx-auto"><div className="h-[390px] sm:h-[500px] rounded-[2.25rem] sm:rounded-[3rem] border-[8px] sm:border-[10px] border-white/10 overflow-hidden bg-white shadow-2xl relative">{heroSlides.map((item, index) => <img key={item.src} src={item.src} alt={item.alt} className={`absolute inset-0 w-full h-full object-contain transition-opacity duration-700 ${index === slide ? 'opacity-100' : 'opacity-0'}`} />)}<button type="button" onClick={() => setSlide(current => (current - 1 + heroSlides.length) % heroSlides.length)} aria-label="Previous image" className="absolute left-3 top-1/2 -translate-y-1/2 h-10 w-10 rounded-full bg-primary-900/75 text-white grid place-items-center backdrop-blur hover:bg-primary-900"><ChevronLeft size={20}/></button><button type="button" onClick={() => setSlide(current => (current + 1) % heroSlides.length)} aria-label="Next image" className="absolute right-3 top-1/2 -translate-y-1/2 h-10 w-10 rounded-full bg-primary-900/75 text-white grid place-items-center backdrop-blur hover:bg-primary-900"><ChevronRight size={20}/></button><div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2 bg-primary-900/60 rounded-full p-2 backdrop-blur">{heroSlides.map((_, index) => <button key={index} type="button" onClick={() => setSlide(index)} aria-label={`Show image ${index + 1}`} className={`h-2 rounded-full transition-all ${index === slide ? 'w-6 bg-secondary-300' : 'w-2 bg-white/70'}`} />)}</div></div><div className="absolute left-4 lg:-left-10 bottom-8 sm:bottom-10 bg-white text-primary-900 rounded-2xl p-3 sm:p-4 shadow-2xl flex items-center gap-3"><div className="h-10 w-10 sm:h-11 sm:w-11 rounded-xl bg-secondary-200 grid place-items-center"><MapPin className="text-secondary-700"/></div><div><strong className="block">10+ local places</strong><span className="text-xs sm:text-sm text-gray-500">ready to discover</span></div></div></div>
      </div>
    </section>
    <section className="section-shell py-20"><div className="flex items-end justify-between mb-9"><div><p className="eyebrow">Pick your kind of day</p><h2 className="text-3xl md:text-5xl font-extrabold mt-3">Explore categories</h2></div><Link className="hidden sm:flex items-center gap-2 font-bold text-primary-700" to="/categories">View all <ArrowRight size={18}/></Link></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{categories.map(([name, Icon])=><Link key={name} to={`/places?category=${name}`} className="bg-white hover:bg-primary-600 focus-visible:bg-primary-600 hover:text-white focus-visible:text-white border border-primary-900/10 hover:border-primary-600 rounded-3xl p-6 min-h-48 flex flex-col justify-between group transition-all duration-300 ease-out hover:-translate-y-2 hover:shadow-xl hover:shadow-primary-900/10 focus-visible:-translate-y-2 focus-visible:ring-4 focus-visible:ring-primary-500/20 outline-none"><div className="bg-primary-50 text-primary-700 group-hover:bg-white/15 group-hover:text-white group-focus-visible:bg-white/15 group-focus-visible:text-white h-12 w-12 rounded-2xl flex items-center justify-center transition-all duration-300 group-hover:scale-110 group-hover:-rotate-3"><Icon size={26}/></div><div><h3 className="text-xl font-bold transition-transform duration-300 group-hover:translate-x-1">{name}</h3><span className="text-sm flex gap-1 items-center mt-1 text-gray-500 group-hover:text-white/75 group-focus-visible:text-white/75 transition-colors">Discover places <ArrowRight size={14} className="group-hover:translate-x-2 transition-transform duration-300"/></span></div></Link>)}</div></section>
    <section className="bg-[#edf2e9] py-20"><div className="section-shell"><div className="flex items-end justify-between mb-9"><div><p className="eyebrow">Worth the short journey</p><h2 className="text-3xl md:text-5xl font-extrabold mt-3">Popular near you</h2></div><Link className="hidden sm:flex items-center gap-2 font-bold text-primary-700" to="/places">All places <ArrowRight size={18}/></Link></div>{places.length ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{places.map(p=><PlaceCard key={p._id} place={p}/>)}</div> : <div className="bg-white border border-dashed border-primary-900/20 rounded-3xl py-16 text-center"><MapPin className="mx-auto text-primary-300" size={40}/><h3 className="text-xl font-bold mt-4">Your places will appear here</h3><p className="text-gray-500 mt-2">Add real attractions from the administrator dashboard.</p></div>}</div></section>
    <section className="section-shell py-20"><div className="bg-secondary-300 rounded-[2.5rem] px-7 py-14 md:p-16 grid md:grid-cols-[1fr_auto] gap-8 items-center"><div><p className="eyebrow !text-primary-800">Make the most of one day</p><h2 className="text-3xl md:text-5xl font-extrabold mt-3 max-w-2xl">Choose the places. We’ll shape the day.</h2><p className="text-primary-900/65 mt-4 text-lg">Build a simple timeline with visit times, a lunch break and a trip summary.</p></div><Link to="/day-planner" className="bg-primary-900 text-white rounded-full px-7 py-4 font-bold flex items-center gap-3 w-max">Start planning <ArrowRight size={19}/></Link></div></section>
  </main>;
};
export default Home;
